[project]
name = "raydium"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "asyncio>=3.4.3",
    "dotenv>=0.9.9",
    "psycopg2>=2.9.10",
    "requests>=2.32.3",
    "urllib3>=2.3.0",
    "websockets>=15.0.1",
]
